name: "Test docker-compose-web-modeler.yml"
on:
  push:
    branches:
      - "**"
jobs:
  test_modeler_yaml:
    uses: ./.github/workflows/template-deploy.yaml
    secrets: inherit
    with:
      compose_args: "-f docker-compose.yml -f docker-compose-web-modeler.yml"
      run_e2e_tests: true
