name: "Test docker-compose-core.yml"
on:
  push:
    branches:
      - "**"
jobs:
  test_core:
    uses: ./.github/workflows/template-deploy.yaml
    secrets: inherit
    with:
      compose_args: "-f docker-compose-core.yml"
      run_e2e_tests: false

